version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Docker/backend.Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./backend/chatbots.db:/app/chatbots.db  # Persist SQLite database

  frontend:
    build:
      context: .
      dockerfile: Docker/frontend.Dockerfile
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
